spring:
  application:
    name: Centralthon

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        generate_statistics: true
    hibernate:
      ddl-auto: none   # 필요 시 update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.hibernate.type: TRACE

# JWT 설정 (env에서 불러오기)
jwt:
  secret: ${JWT_SECRET}
  access-exp-millis: ${JWT_ACCESS_EXP_MILLIS:86400000}

# Jackson 설정은 JacksonConfig에서 처리
# 업로드 디렉토리
upload-dir: ${APP_UPLOAD_DIR}

app:
  upload:
    path: ${APP_UPLOAD_DIR}/crop/

# 파라미터 스토어 (옵션)
parameter-store:
  enabled: ${PARAMETER_STORE_ENABLED:false}
  region: ${AWS_REGION:us-east-1}
  prefix: ${PARAMETER_PREFIX:/planty}

# AI 모델 및 파라미터 설정
ai:
  openai:
    api-key: ${OPENAI_API_KEY}
    timeout: 60
    maxRetries: 3
    enableLogging: false
  crop-registration:
    model: gpt-4o-mini
    max-tokens: 100000
    temperature: 0.1
  crop-diagnosis:
    model: gpt-4o
    max-tokens: 100000
    temperature: 0.2
