spring:
  application:
    name: Centralthon

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Centralthon?serverTimezone=UTC
    username: back
    password: 1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        generate_statistics: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE      # 파라미터 값 바인딩 로그
    org.hibernate.orm.jdbc.extract: TRACE   # 결과 추출 로그
    org.hibernate.type: TRACE               # (보조) 타입 바인딩 로그

jwt:
  secret: "change-this-to-a-very-long-random-secret-at-least-256-bits"
  access-exp-millis: 86400000     # 1시간

app:
  upload-dir: uploads